const defaultKeywords = [
  'Ohio University',
  'Athens Central Hotel',
  'Athens',
  'Ohio',
  'Hotel',
  'Athens Central',
  'Hotels in Athens',
  'Hotels',
  'Boutique Hotels',
  'Affordable Hotels',
  'Fancy Hotels',
  'Fancy Hotel',
  'Affordable Hotel',
  'Bobcats',
  'United States',
  'Boutique',
  'OU Alumni Hotel',
  'Ohio University Alumni Hotel',
  "Mom's weekend",
  'Moms Weekend',
  'Dads weekend',
  "Dad's weekend",
  'OU Alumni',
  'Ohio University Alumni',
  'Parents Weekend',
  'Graduation weekend',
  'Prokos Rentals',
  'Court Street',
  'Hotel close to bars',
  'Near Court Street',
  'Modern hotel',
  'Beautiful hotel',
  'Upgraded Showers',
  'Athens, Ohio',
  'USA',
  'Greece',
  'Greek Hotel',
  'Zeus King Room',
  'Athena Suite',
  'Cleo Double Queen Room',
  'State Street',
  "Near Broney's",
  '4 star hotel',
  '5 star hotel',
  'Free parking',
];

export default defaultKeywords;
